### ISSUE TITLE
Zone .hasDst() always returning true

### ISSUE THREAD

**Issue by mbuster** [SpiritIT/timezonecomplete#33]
hasDst always seems to return true, regardless of timezone. Try Phoenix, Honolulu, etc. These TZs don't observe DST, but library claims they do.

var timezonecomplete = require("timezonecomplete")
var db = timezonecomplete.TzDatabase.instance();

var p = 'America/Phoenix';
var z = timezonecomplete.zone(p);
var hasDST = z.hasDst(p);
console.log(p,hasDST);

**Comment by rogierschouten** [comment]
Phoenix did observe DST in the past. That's why the function returns true - it is a hint to the programmer that you cannot calculate with local dates for Phoenix because there are DST transitions in its history.

Try it e.g. with UTC or GMT+0, it will return false.

If you need to know if the time zone has DST _this year_, then you could instantiate different DateTime objects (e.g. in january and in july) and compare their offset() return values.  **Note** however that some time zones (e.g. in some Muslim countries) have DST twice in a year because they go back to winter time during Ramadan. Hence you have to pick your dates a bit carefully.



From the TZ database:
```
# From Paul Eggert (2002-10-20):
#
# The information in the rest of this paragraph is derived from the
# Daylight Saving Time web page
# <http://www.dlapr.lib.az.us/links/daylight.htm> (2002-01-23)
# maintained by the Arizona State Library, Archives and Public Records.
# Between 1944-01-01 and 1944-04-01 the State of Arizona used standard
# time, but by federal law railroads, airlines, bus lines, military
# personnel, and some engaged in interstate commerce continued to
# observe war (i.e., daylight saving) time.  The 1944-03-17 Phoenix
# Gazette says that was the date the law changed, and that 04-01 was
# the date the state's clocks would change.  In 1945 the State of
# Arizona used standard time all year, again with exceptions only as
# mandated by federal law.  Arizona observed DST in 1967, but Arizona
# Laws 1968, ch. 183 (effective 1968-03-21) repealed DST.
#
# Shanks says the 1944 experiment came to an end on 1944-03-17.
# Go with the Arizona State Library instead.

# Zone	NAME		GMTOFF	RULES	FORMAT	[UNTIL]
Zone America/Phoenix	-7:28:18 -	LMT	1883 Nov 18 11:31:42
			-7:00	US	M%sT	1944 Jan  1  0:01
			-7:00	-	MST	1944 Apr  1  0:01
			-7:00	US	M%sT	1944 Oct  1  0:01
			-7:00	-	MST	1967
			-7:00	US	M%sT	1968 Mar 21
			-7:00	-	MST
```

I'm closing this issue but please feel free to re-open if something is really amiss or you need something else, please re-open.
