### ISSUE TITLE
Doc: DateTime constructor throws

### ISSUE THREAD

**Issue by ig3** [SpiritIT/timezonecomplete#57]
This is a minor issue but it confused when I tried to understand how to code to handle errors in the constructors.

The documentation for the [DateTime constructor](https://rawcdn.githack.com/SpiritIT/timezonecomplete/master/doc/typedoc/classes/datetime.html#constructor) indicates that it throws nothing.

In fact, the [various constructors](https://github.com/SpiritIT/timezonecomplete/blob/0fe27bc/src/lib/datetime.ts#L217) do throw various errors.

Maybe I misunderstand the documentation but I think it would be less confusing if it indicated that the constructors do throw errors and some way to learn what those errors are.

There is a link to the source and the errors are identified in the source. Even replacing 'nothing' with 'yes' or 'errors' would be an improvement.

**Comment by rogierschouten** [comment]
I'm sorry it got you confused.  The documentation is actually very precise, it lists for every combination of arguments what errors could be thrown.   The constructor without arguments does not throw. 

Maybe the confusion is because TypeScript and JavaScript do not support proper method overloading - in implementation, it is just one constructor. And hence you expected only one bit of documentation. 

However, TypeScript and TypeDoc do allow for different method signatures, which are also statically checked. Different method signatures need different documentation, and hence it makes sense to also make the error handling specific to each signature. 

I am at a loss on how to improve this.  If I were to put anything else than 'nothing' for the argument-less constructor, I would be going against all documentation for all methods and make all documentation inconsistent.   

I am closing this issue for now - but feel free to reopen with ideas that keep everything consistent.

**Comment by ig3** [comment]
@rogierschouten 

Thank you for your response. I went to have another look and realized for the first time that in the panel for the DateTime constructor I am able to click on the little blue circle with the white cross on it, to the left of the constructor syntax example, and when I do the text below the set of constructors changes. I had been looking only at the bottom text that appears by default, not knowing that I could change it. By default, the description is for the first constructor which, as you say, throws nothing.

I had, to date, often found the API documentation confusing and unhelpful but I expect that with this new insight it will be much more helpful: there is a lot of information I simply wasn't seeing before ;-)

Thank you for prompting me to have another look and more persistently tinker to find what you said was there. It was, of course, there all along.

Some of the little icons I can click on to get more/different information. Others don't seem to do anything when I click on them (for example the solid purple circles to the left of some of the entries). No doubt these icons all have meaning. Is there some documentation of them somewhere? I see the legend at the bottom of the main page that gives them suggestive titles, but clicking on them doesn't lead me to pages that describe their meaning in more detail or, more importantly, their function in the documentation interface. I am now wondering what other features of the documentation I have been missing.

**Comment by rogierschouten** [comment]
Hi @ig3   I use TypeDoc to generate the docs, so you might find some info here: http://typedoc.org/
